# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
env NPM_CONFIG_LOGLEVEL=warn
WORKDIR /app

# Copy package.json and tsconfig
COPY package.json tsconfig.json ./
# Copy source code
COPY src ./src

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts \
    && npm run build \
    && npm prune --production

# Default command
CMD ["node", "dist/index.js"]
